import axios from 'axios';
import React, { useState, useEffect } from 'react';
import { jsPDF } from "jspdf";
import { 
  FiAlertTriangle, 
  FiAlertCircle, 
  FiInfo, 
  FiCheckCircle, 
  FiMapPin, 
  FiDownload, 
  FiShare2, 
  FiBell, 
  FiRefreshCw, 
  FiChevronDown, 
  FiChevronUp,
  FiExternalLink
} from 'react-icons/fi';
import { useSelector } from 'react-redux';
import { MdDelete } from 'react-icons/md';
import toast, { Toaster } from 'react-hot-toast';

const severityStyles = {
  critical: {
    bg: "bg-error",
    text: "text-error-content",
    border: "border-error",
    icon: <FiAlertTriangle className="text-2xl" />,
    title: "EVACUATE IMMEDIATELY",
    priority: 1
  },
  high: {
    bg: "bg-warning",
    text: "text-warning-content",
    border: "border-warning",
    icon: <FiAlertTriangle className="text-2xl" />,
    title: "HIGH RISK ALERT",
    priority: 2
  },
  medium: {
    bg: "bg-accent",
    text: "text-accent-content",
    border: "border-accent",
    icon: <FiAlertCircle className="text-2xl" />,
    title: "CAUTION ADVISED",
    priority: 3
  },
  low: {
    bg: "bg-info",
    text: "text-info-content",
    border: "border-info",
    icon: <FiInfo className="text-2xl" />,
    title: "LOW RISK NOTICE",
    priority: 4
  },
  safe: {
    bg: "bg-success",
    text: "text-success-content",
    border: "border-success",
    icon: <FiCheckCircle className="text-2xl" />,
    title: "ALL CLEAR",
    priority: 5
  }
};
;
const handleDownload = (alert2) => {
  
  const doc = new jsPDF();
  
  const margin = 20;
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  doc.setFillColor(211, 47, 47);
  doc.rect(0, 0, pageWidth, 15, 'F');
  
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(40, 40, 40);
  doc.text('LANDSLIDE RISK ALERT REPORT', pageWidth / 2, 30, { align: 'center' });
  
 
  doc.setFillColor(240, 240, 240);
  doc.roundedRect(margin, 40, pageWidth - margin * 2, 15, 3, 3, 'F');
  doc.setDrawColor(200, 200, 200);
  doc.roundedRect(margin, 40, pageWidth - margin * 2, 15, 3, 3, 'D');
  doc.setFontSize(16);
  doc.setTextColor(0, 0, 0);
  doc.text(`📍 ${alert2.locationName || 'Unknown Location'}`, margin + 10, 50);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('ALERT DETAILS', margin, 70);
  
  doc.setFont('helvetica', 'normal');
  const detailsYStart = 80;
  const details = [
    { icon: '🗺️', text: `Coordinates: ${alert2.location?.latitude || "N/A"}, ${alert2.location?.longitude || "N/A"}` },
    { icon: '⚠️', text: `Severity: ${alert2.severity.toUpperCase()}` },
    { icon: '📅', text: `Date: ${new Date(alert2.createdAt).toLocaleString()}` },
    { icon: '👤', text: `Reported by: ${alert2.user?.fullName || "Unknown"}` },
    { icon: '📝', text: `Description: ${alert2.description || "No additional details provided"}` }
  ];
  
  details.forEach((detail, i) => {
    doc.text(`${detail.icon} ${detail.text}`, margin + 5, detailsYStart + (i * 7));
  });
  
  const severityColors = {
    high: [211, 47, 47],   
    medium: [255, 165, 0], 
    low: [56, 142, 60]    
  };
  const severityColor = severityColors[alert2.severity.toLowerCase()] || [100, 100, 100];
  doc.setFillColor(...severityColor);
  doc.roundedRect(pageWidth - margin - 50, 65, 50, 15, 7, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.text(alert2.severity.toUpperCase(), pageWidth - margin - 25, 75, { align: 'center' });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(0, 0, 0);
  doc.text('RISK FACTORS', margin, 120);
  
  doc.setFont('helvetica', 'normal');
  const riskFactors = [
    '• Steep terrain slope',
    '• Recent heavy rainfall',
    '• Soil composition',
    '• Historical landslide activity'
  ];
  riskFactors.forEach((factor, i) => {
    doc.text(factor, margin + 5, 130 + (i * 7));
  });
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(211, 47, 47);
  doc.text('SAFETY RECOMMENDATIONS', margin, 160);
  
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(0, 0, 0);
  const recommendations = [
    '• Avoid the area until further notice',
    '• Monitor local authorities for updates',
    '• Prepare emergency evacuation plan',
    '• Secure loose objects that could slide',
    '• Report any new ground movement'
  ];
  recommendations.forEach((rec, i) => {
    doc.text(rec, margin + 5, 170 + (i * 7));
  });
  
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Landslide Disaster Management System', pageWidth / 2, pageHeight - 15, { align: 'center' });
  doc.text(`Report ID: ${alert2.id || 'N/A'} | ${new Date().toLocaleString()}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  doc.setDrawColor(211, 47, 47);
  doc.setLineWidth(0.5);
  doc.rect(10, 10, pageWidth - 20, pageHeight - 20);
  
  const fileName = `Landslide_Alert_${alert2.locationName.replace(/\s+/g, '_')}_${new Date().getTime()}.pdf`;
  doc.save(fileName);
};
const formatTime = (date) => {    
  const now = new Date();
  const diffInHours = Math.floor((now - new Date(date)) / (1000 * 60 * 60));
  
  if (diffInHours < 1) {
    const diffInMinutes = Math.floor((now - new Date(date)) / (1000 * 60));
    return `${diffInMinutes} min ago`;
  } else if (diffInHours < 24) {
    return `${diffInHours} hour${diffInHours > 1 ? 's' : ''} ago`;
  } else {
    return new Date(date).toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
  }
};

const AlertCard = ({ alert, expanded, toggleExpand }) => {
   const baseUrl = useSelector((state) => state.base.baseUrl);
  const style = severityStyles[alert.severity.toLowerCase()] || severityStyles.medium;
 
  const handleDeleteAlert = async (alertId) =>{
    try {
      const res = await axios.delete(`${baseUrl}/api/alerts/deleteAlert/${alertId}`, {
        withCredentials : true,
      })
      if(res.data){
        toast.success(res.data.message || "Alert deleted Successfully")
      }
    } catch (error) {
      toast.error(res.data.message || "Something went wrong in alert deleting")
    }
  } 
  return (
    <div className={`border rounded-lg overflow-hidden shadow-sm hover:shadow-md transition-shadow ${style.border} ${expanded ? 'ring-2 ring-base-300' : ''}`}>
   <Toaster position="top-center" reverseOrder={false} />
      <div 
        className={`flex items-center justify-between p-4 cursor-pointer ${style.bg} ${style.text}`}
        onClick={toggleExpand}
      >
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded-md bg-base-100/20">
            {style.icon}
          </div>
          <div>
            <h3 className="font-semibold">{style.title}</h3>
            <p className="text-sm opacity-90">{alert.locationName}</p>
          </div>
        </div>
        <div className="flex items-center space-x-2">
          <span className="text-xs bg-base-100/20 px-2 py-1 rounded">
            {formatTime(alert.updatedAt)}
          </span>
          {expanded ? <FiChevronUp /> : <FiChevronDown />}
        </div>
      </div>

      {expanded && (
        <div className="p-4 bg-base-100">
          <div className="mb-4">
            <div className="flex items-center text-sm text-base-content/70 mb-1">
              <FiMapPin className="mr-1" />
              <span>{alert.coordinates.lat.toFixed(4)}, {alert.coordinates.lng.toFixed(4)}</span>
            </div>
            <h4 className="font-medium text-base-content mb-2">Alert Details</h4>
            <p className="text-sm text-base-content/90 mb-4">
              {alert.severity === 'critical' ? 'Immediate evacuation required' : 
               alert.severity === 'high' ? 'High risk area - avoid travel' :
               alert.severity === 'medium' ? 'Exercise caution in this area' :
               alert.severity === 'low' ? 'Low risk but stay alert' :
               'Area is currently safe'}
            </p>
            
            {alert.severity.toLowerCase() === 'critical' && (
              <div className="bg-error/10 border-l-4 border-error p-3 mb-4">
                <div className="flex items-center">
                  <FiAlertTriangle className="text-error mr-2" />
                  <p className="text-sm font-medium text-error">Evacuation orders are in effect for this area.</p>
                </div>
              </div>
            )}
          </div>

          <div className="grid grid-cols-2 gap-4 mb-4">
            <div className="border rounded p-3">
              <p className="text-xs text-base-content/50 mb-1">Severity Level</p>
              <p className={`font-medium ${style.text}`}>{alert.severity.toUpperCase()}</p>
            </div>
            <div className="border rounded p-3">
              <p className="text-xs text-base-content/50 mb-1">Reported By</p>
              <p className="font-medium">{alert.user?.fullName || 'System'}</p>
            </div>
            <div className="border rounded p-3">
              <p className="text-xs text-base-content/50 mb-1">Last Updated</p>
              <p className="font-medium">{new Date(alert.updatedAt).toLocaleString()}</p>
            </div>
            <div className="border rounded p-3">
              <p className="text-xs text-base-content/50 mb-1">Created At</p>
              <p className="font-medium">{new Date(alert.createdAt).toLocaleString()}</p>
            </div>
          </div>

          <div className="flex flex-wrap gap-2">
            <button className="btn btn-outline btn-sm">
              <FiShare2 className="mr-2" />
              Share
            </button>
            <button className="btn btn-outline btn-sm" onClick={() =>handleDownload(alert)}>
              <FiDownload className="mr-2" />
              Download Report
            </button>
            <button onClick={() => handleDeleteAlert(alert._id)} className="btn btn-primary btn-sm">
              <MdDelete className="mr-2" size={20} />
              Remove Alert
            </button>
            <button className="btn btn-ghost btn-sm">
              <FiExternalLink className="mr-2" />
              View Details
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

const LiveAlerts = () => {
  const [expandedCard, setExpandedCard] = useState(null);
  const [autoRefresh, setAutoRefresh] = useState(true);
  const [isLoading, setIsLoading] = useState(false);
  const [alerts, setAlerts] = useState([]);
  const [error, setError] = useState(null);
  const baseUrl = useSelector((state) => state.base.baseUrl);

  const fetchAlerts = async () => {
    setIsLoading(true);
    setError(null);
    try {
      const res = await axios.get(`${baseUrl}/api/alerts/allAlertOngoing`, {
        withCredentials: true
      });
      if (res.data && res.data.alert2) {
        setAlerts(res.data.alert2);
      }
    } catch (error) {
      console.error('Error fetching alerts:', error);
      setError('Failed to load alerts. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchAlerts();
    
    if (autoRefresh) {
      const interval = setInterval(fetchAlerts, 30000);
      return () => clearInterval(interval);
    }
  }, [autoRefresh, baseUrl]);

  const toggleExpand = (id) => {
    setExpandedCard(expandedCard === id ? null : id);
  };

  const handleRefresh = () => {
    fetchAlerts();
  };

  const sortedAlerts = [...alerts].sort((a, b) => {
    return severityStyles[a.severity.toLowerCase()].priority - 
           severityStyles[b.severity.toLowerCase()].priority;
  });

  return (
    <div className="min-h-screen bg-base-200">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        <header className="mb-8">
          <div className="flex flex-col md:flex-row md:items-center md:justify-between">
            <div>
              <h1 className="text-3xl font-bold text-base-content">Landslide Risk Monitoring</h1>
              <p className="mt-2 text-base-content/70">
                Real-time alerts for the Darjeeling Himalayan region
              </p>
            </div>
            <div className="mt-4 md:mt-0">
              <button 
                className="btn btn-outline"
                onClick={handleRefresh}
                disabled={isLoading}
              >
                <FiRefreshCw className={`mr-2 ${isLoading ? 'animate-spin' : ''}`} />
                {isLoading ? 'Refreshing...' : 'Refresh Data'}
              </button>
            </div>
          </div>
        </header>

        <div className="bg-base-100 p-4 rounded-lg shadow-sm border border-base-300 mb-6">
          <div className="flex flex-wrap items-center justify-between gap-4">
            <div className="flex items-center space-x-4">
              <label className="label cursor-pointer">
                <input 
                  type="checkbox" 
                  className="toggle toggle-primary"
                  checked={autoRefresh}
                  onChange={() => setAutoRefresh(!autoRefresh)}
                />
                <span className="label-text ml-2">Auto-refresh (30s)</span>
              </label>
            </div>
            <div className="text-sm text-base-content/50">
              Last updated: {new Date().toLocaleTimeString()}
            </div>
          </div>
        </div>

        {error && (
          <div className="alert alert-error mb-6">
            <svg xmlns="http://www.w3.org/2000/svg" className="stroke-current shrink-0 h-6 w-6" fill="none" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
            </svg>
            <span>{error}</span>
          </div>
        )}

        <div className="grid grid-cols-2 md:grid-cols-5 gap-4 mb-6">
          {Object.entries(severityStyles).map(([severity, style]) => (
            <div 
              key={severity} 
              className={`p-3 rounded-lg border ${style.border} ${style.bg} ${style.text}`}
            >
              <div className="flex items-center justify-between">
                <span className="text-sm font-medium">{style.title}</span>
                <span className="text-xs bg-base-100/20 px-2 py-1 rounded">
                  {alerts.filter(a => a.severity.toLowerCase() === severity).length}
                </span>
              </div>
            </div>
          ))}
        </div>

        {isLoading ? (
          <div className="flex justify-center items-center py-20">
            <span className="loading loading-spinner loading-lg text-primary"></span>
          </div>
        ) : alerts.length > 0 ? (
          <div className="space-y-4">
            {sortedAlerts.map(alert => (
              <AlertCard
                key={alert._id}
                alert={alert}
                expanded={expandedCard === alert._id}
                toggleExpand={() => toggleExpand(alert._id)}
              />
            ))}
          </div>
        ) : (
          <div className="text-center py-16 bg-base-100 rounded-lg border border-base-300">
            <FiCheckCircle className="mx-auto h-12 w-12 text-success" />
            <h3 className="mt-4 text-lg font-medium text-base-content">No active alerts</h3>
            <p className="mt-2 text-base-content/70">All regions are currently within normal parameters.</p>
          </div>
        )}

        <footer className="mt-12 pt-6 border-t border-base-300">
          <div className="flex flex-col md:flex-row justify-between items-center">
            <p className="text-sm text-base-content/50">
              © {new Date().getFullYear()} Landslide Watch Early Warning System
            </p>
            <div className="mt-4 md:mt-0 flex space-x-6">
              <a href="#" className="text-sm text-base-content/50 hover:text-base-content">About</a>
              <a href="#" className="text-sm text-base-content/50 hover:text-base-content">API</a>
              <a href="#" className="text-sm text-base-content/50 hover:text-base-content">Contact</a>
              <a href="#" className="text-sm text-base-content/50 hover:text-base-content">Privacy</a>
            </div>
          </div>
        </footer>
      </div>
    </div>
  );
};

export default LiveAlerts;